version: "3" 
services:

  nginx:
    container_name: molly_2_nginx
    image: nginx:1.13
    volumes:
      - "./:/var/www/html"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: molly_2_php
    build:
      context: ./config/php
    volumes:
      - "./:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
  
  mysql:
    container_name: molly_2_mysql
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./config/mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

volumes:
  db_data:
